# 4.6 - 2D Numpy

Hands-on Lab: 2D Numpy in Python

## Tujuan
- Membuat dan mengakses array NumPy 2 dimensi (matriks)
- Operasi dasar matriks: addition, scalar multiplication, Hadamard product, dot product
- Transpose matriks

In [1]:
import numpy as np

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [2]:
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [3]:
print("ndim:", A.ndim)   # jumlah dimensi/axes
print("shape:", A.shape) # (baris, kolom)
print("size:", A.size)    # total elemen

ndim: 2
shape: (3, 3)
size: 9


In [4]:
# baris index 1, kolom index 2
print(A[1, 2])
print(A[1][2])   # cara alternatif, hasil sama

23
23


In [5]:
A[0][0]

np.int64(11)

In [6]:
A[0][0:2]

array([11, 12])

In [7]:
A[0:2, 2]

array([13, 23])

## Basic Operations

In [9]:
X = np.array([[1, 0], [0, 1]])
Y = np.array([[2, 1], [1, 2]])

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [10]:
Y = np.array([[2, 1], [1, 2]])
Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [11]:
X = np.array([[1, 0], [0, 1]])
Y = np.array([[2, 1], [1, 2]])

Z = X * Y   # perkalian per posisi, BUKAN perkalian matriks matematis
Z

array([[2, 0],
       [0, 2]])

In [12]:
A = np.array([[0, 1, 1], [1, 0, 1]])
B = np.array([[1, 1], [1, 1], [-1, 1]])

Z = np.dot(A, B)   # A shape (2,3), B shape (3,2) -> hasil shape (2,2)
Z

array([[0, 2],
       [0, 2]])

In [13]:
np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [14]:
C = np.array([[1, 1], [2, 2], [3, 3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [15]:
C.T   # tukar posisi baris jadi kolom, dan sebaliknya

array([[1, 2, 3],
       [1, 2, 3]])

## Quiz on 2D Numpy Array

In [16]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
A.size

12

In [18]:
A[0][0:2]

array([1, 2])

In [19]:
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
X = np.dot(A, B)
X

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])